spring:
  datasource:
    tomcat:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-active: 100
      initial-size: 10
      min-idle: 10
      max-idle: 20
      validation-query: select 1
      test-while-idle: true

server:
  port: 8081
  tomcat:
    accept-count: 100
    max-threads: 200
    max-connections: 8192

management:
  endpoints:
    web:
      exposure:
        include: prometheus,metrics  # 开启的端点
    jmx:
      exposure:
        include: prometheus,metrics  # 开启的端点
  server:
    port: 8081  # 可重置管理端口

