spring:
  datasource:
    tomcat:
      url: jdbc:mysql://47.93.163.210:3306/test
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-active: 100
      initial-size: 10
      min-idle: 10
      max-idle: 20
      validation-query: select 1
      test-while-idle: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: prometheus,metrics  # 开启的端点
    jmx:
      exposure:
        include: prometheus,metrics  # 开启的端点
  server:
    port: 8082  # 可重置管理端口

